stages:
  - build
  - setup
  - test
  - deploy

tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

setup:
  stage: setup
  script:
    - cd client
    - npm install
  cache:
    paths:
      - client/node_modules/
  artifacts:
    paths:
      - client/node_modules/

junit:
  stage: test
  script:
    - cd server
    - ./gradlew test

jest:
  stage: test
  script:
    - cd client
    - npm run test

deploy-test-server:
  stage: deploy
  script:
    # Create artifact
    - cd server
    - ./gradlew bootJar
    # Create images directory
    - mkdir -p /home/gitlab-runner/test/images/profile/
    - mkdir -p /home/gitlab-runner/test/images/activity/
    # Move artifact to clean directory
    - rm -rf /home/gitlab-runner/test-server/
    - mkdir -p /home/gitlab-runner/test-server/
    - cp -r ./build/libs /home/gitlab-runner/test-server
    # Add environment variables to file
    - echo "export DB_USER=$DB_USER" > vars.config
    - echo "export DB_PASSWORD=$DB_PASSWORD" >> vars.config
    - cp vars.config /home/gitlab-runner/test-server
    # Update bash script and restart service
    - rm -f /home/gitlab-runner/runTestServer.sh || true
    - cp ../deployment-scripts/runTestServer.sh /home/gitlab-runner/runTestServer.sh
    - sudo systemctl restart testServer
  only:
    refs:
      - dev



deploy-test-client:
  stage: deploy
  script:
    # Create artifact
    - cd client
    - rm -rf ./dist
    - npm run build
    # Move artifact to clean directory
    - rm -rf /home/gitlab-runner/test-client/
    - mkdir -p /home/gitlab-runner/test-client/
    - cp -r ./dist /home/gitlab-runner/test-client
    # Update bash script and restart service
    - rm -f /home/gitlab-runner/runTestClient.sh || true
    - cp ../deployment-scripts/runTestClient.sh /home/gitlab-runner/runTestClient.sh
    - sudo systemctl restart testClient
  only:
    refs:
      - dev




deploy-prod-server:
  stage: deploy
  script:
    # Create artifact
    - cd server
    - ./gradlew bootJar
    # Create images directory
    - mkdir -p /home/gitlab-runner/prod/images/profile/
    - mkdir -p /home/gitlab-runner/prod/images/activity/
    # Move artifact to clean directory
    - rm -rf /home/gitlab-runner/prod-server/
    - mkdir -p /home/gitlab-runner/prod-server/
    - cp -r ./build/libs /home/gitlab-runner/prod-server
    # Add environment variables to file
    - echo "export DB_USER=$DB_USER" > vars.config
    - echo "export DB_PASSWORD=$DB_PASSWORD" >> vars.config
    - cp vars.config /home/gitlab-runner/prod-server
    # Update bash script and restart service
    - rm -f /home/gitlab-runner/runProdServer.sh || true
    - cp ../deployment-scripts/runProdServer.sh /home/gitlab-runner/runProdServer.sh
    - sudo systemctl restart prodServer
  only:
    refs:
      - master
      - tags



deploy-prod-client:
  stage: deploy
  script:
    # Create artifact
    - cd client
    - rm -rf ./dist
    - npm run build-prod
    # Move artifact to clean directory
    - rm -rf /home/gitlab-runner/prod-client/
    - mkdir -p /home/gitlab-runner/prod-client/
    - cp -r ./dist /home/gitlab-runner/prod-client
    # Update bash script and restart service
    - rm -f /home/gitlab-runner/runProdClient.sh || true
    - cp ../deployment-scripts/runProdClient.sh /home/gitlab-runner/runProdClient.sh
    - sudo systemctl restart prodClient
  only:
    refs:
      - master
      - tags



