package com.springvuegradle.team6.services;

import com.springvuegradle.team6.security.ConfigProperties;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.MailException;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSenderImpl;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;

/**
 * This service is used to send Emails.
 */
@Service("EmailService")
public class EmailService {

    @Autowired
    private JavaMailSenderImpl emailSender;

    @Autowired
    ConfigProperties configProperties;

    /**
     * Method to send email when user forgets their password.
     * @param to Recipient email
     * @param subject text to put in the subject of the email
     * @param token the Password token generated by the back end
     * @param userName the name of the recipient
     */
    public boolean sendPasswordTokenEmail(String to, String subject, String token, String userName) {
        emailSender.setUsername(configProperties.getUsername());
        emailSender.setPassword(configProperties.getPassword());
        String url = configProperties.getUrl() + token;
        try {
            MimeMessage message = emailSender.createMimeMessage();
            SimpleMailMessage message1 = new SimpleMailMessage();
            message.setFrom("no_reply@edmun.com");
            MimeMessageHelper helper = new MimeMessageHelper(message);

            helper.setFrom("no_reply@edmun.com");
            helper.setTo(to);
            helper.setSubject(subject);
            helper.setText("<html><body>Hi, " + userName + ". <br><br>Click the link below to reset your password. <br><br>" +
                configProperties.getUrl() + "resetpassword/" + token + "</body></html>", true);

            emailSender.send(message);
            return true;
        } catch (MailException | MessagingException exception) {
            exception.printStackTrace();
            return false;
        }
    }
}
